---

- name: installing clod-watch-agent
  ansible.builtin.yum:
    name: amazon-cloudwatch-agent
    state: latest

- name: updating os
  ansible.builtin.yum:
    name: "*"
    state: latest 
- name: install collectd  package
  ansible.builtin.yum:
    name: collectd 
    state: latest
    update_cache: yes


